//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace WebApplication2
{
    public partial class AñadirEquipo
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblTorneoActual;

        protected global::System.Web.UI.WebControls.ValidationSummary vsErrores;

        protected global::System.Web.UI.WebControls.Panel pnlMensajeExito;
        protected global::System.Web.UI.WebControls.Label lblMensajeExito;

        protected global::System.Web.UI.WebControls.Panel pnlMensajeError;
        protected global::System.Web.UI.WebControls.Label lblMensajeError;

        protected global::System.Web.UI.WebControls.TextBox txtCodigoEquipo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCodigoEquipo;

        protected global::System.Web.UI.WebControls.TextBox txtNombreEquipo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombreEquipo;

        protected global::System.Web.UI.WebControls.TextBox txtMovilEquipo;
        protected global::System.Web.UI.WebControls.TextBox txtContactoEquipo;

        protected global::System.Web.UI.WebControls.Button btnGuardarEquipo;
    }
}
