//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace WebApplication2
{
    public partial class ListaEquipos
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblTorneo;
        protected global::System.Web.UI.WebControls.Panel pnlMensajeError;
        protected global::System.Web.UI.WebControls.Label lblMensajeError;
        protected global::System.Web.UI.WebControls.Repeater rptEquipos;
        protected global::System.Web.UI.WebControls.Panel pnlNoData;
    }
}
